# Generated by Django 4.2.30 on 2026-06-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('clothing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mock_name', models.CharField(max_length=255)),
                ('mock_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('recommended_ind', models.BooleanField()),
                ('positive_feedback_count', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
    ]
