# Generated by Django 4.2.30 on 2026-06-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_review_cleaned_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_sentiments', models.JSONField(default=list)),
                ('competitor_ml_sentiments', models.JSONField(default=list)),
                ('pros', models.JSONField(default=list)),
                ('cons', models.JSONField(default=list)),
                ('final_recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_analyses', to='products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='products.product')),
            ],
        ),
    ]
